url18 <- 'http://www.espn.com/nba/salaries/_/year/2019'
url19 <- 'http://www.espn.com/nba/salaries'
urlslry <- 'https://www.basketball-reference.com/contracts/players.html'
statsUrl1head <- 'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=PerGame&Scope=S&Season=200'
statsUrl1tail <- '&SeasonType=Regular+Season&StatCategory=PTS'
url0910 <- 'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=PerGame&Scope=S&Season=2009-10&SeasonType=Regular+Season&StatCategory=PTS'
statsUrl2head <- 'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=PerGame&Scope=S&Season=20'
statsUrl2tail <- '&SeasonType=Regular+Season&StatCategory=PTS'